# This is a basic workflow to help you get started with Actions

name: Run

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      NGROK_KEY: ${{ secrets.NGROK_KEY }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      #- name: Install java
      #  run: sudo apt update && sudo apt install openjdk-21-jdk
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
          
      # Runs a set of commands using the runners shell
      - name: Setup ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar xvzf ngrok-v3-stable-linux-amd64.tgz

      - name: Setup server
        run: |
          mkdir mc
          cd mc
          wget https://piston-data.mojang.com/v1/objects/450698d1863ab5180c25d7c804ef0fe6369dd1ba/server.jar
          echo "eula=true" > eula.txt

      - name: Run
        run: |
          ./ngrok config add-authtoken $NGROK_KEY
          ./ngrok tcp 25565 &
          sleep 5
          cd mc
          java --version
          java -jar server.jar
